# Uncomment the next line to define a global platform for your project
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks

platform :ios, '9.0'

use_frameworks!

target 'DYLive' do

pod 'Alamofire', '~> 4.4'


  # Pods for DYLive

  target 'DYLiveTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DYLiveUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
